// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package tech.claudioed.grpc.vertx;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.MessageRequest)
    com.google.protobuf.MessageOrBuilder {
}
