// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package tech.claudioed.grpc.vertx;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_MessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\007message\"\020\n\016MessageReque" +
      "st\"B\n\017MessageResponse\022\017\n\007message\030\001 \001(\t\022\r" +
      "\n\005stack\030\002 \001(\t\022\017\n\007version\030\003 \001(\t2L\n\007Messag" +
      "e\022A\n\ngetMessage\022\027.message.MessageRequest" +
      "\032\030.message.MessageResponse\"\000B5\n\031tech.cla" +
      "udioed.grpc.vertxB\014MessageProtoP\001\242\002\007MESS" +
      "AGEb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_MessageRequest_descriptor,
        new java.lang.String[] { });
    internal_static_message_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_MessageResponse_descriptor,
        new java.lang.String[] { "Message", "Stack", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
