// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package tech.claudioed.grpc.vertx;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string stack = 2;</code>
   */
  java.lang.String getStack();
  /**
   * <code>string stack = 2;</code>
   */
  com.google.protobuf.ByteString
      getStackBytes();

  /**
   * <code>string version = 3;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 3;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
